CREATE PROC FI_SP_IncBeneficiario
	@IDCLIENTE     BIGINT,
    @CPF           VARCHAR (14),
    @NOME          VARCHAR (50)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (IDCLIENTE, CPF, NOME) 
	VALUES (@IDCLIENTE,@CPF,@NOME)

	SELECT SCOPE_IDENTITY()
END